root=/user

spring:
  profiles: cloud
  cloud:
    config:
      uri: http://localhost:8887

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ImTheUserService
    non-secure-port: 80
