root: /user

server:
  port: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    non-secure-port: 80
    
spring:
 data:
   mongodb:
     host: 192.168.99.100
     port: 27017
     database: userdb
